### PR TITLE
Add newty.dev

### PR DESCRIPTION
**Pull request by newtykip**
hello :3

### CODE REVIEW

**Review by isabelroses — APPROVED** [review]
Welcome aboard, lovely website by the way

**Comment by newtykip** [comment]
Thank you :]

**Comment by uncenter** [comment]
Hihi I just found your website from the webring and I just wanted to say I love it as well :3 so many nice details, really pretty!

**Comment by newtykip** [comment]
Thank you guys for the warm welcome <|:]

**Pull request merged**
